# Site settings
title: "U.S. Fish & Wildlife Service: Southeast Region"
email: webmaster@fws.gov
description: > # this means to ignore newlines until "baseurl:"
  The Southeast Region covers an area more than 430,000 
  square miles, which includes the states of AL, AR, FL, GA, KY, 
  LA, MS, NC, SC, TN, as well as the Commonwealth of Puerto Rico 
  and the Virgin Islands.

baseurl: "/southeast/" # the subpath of your site, e.g. /blog/
url: "http://fws.gov" # the base hostname & protocol for your site

excerpt_separator: <!--more-->

# Social
twitter_username: usfwssoutheast
github_username:  usfws
facebook_username: usfwssoutheast
flickr_username: usfwssoutheast

# Build settings
markdown: kramdown

# Exclusions
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME
  src/,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  readme.md,
  southeast.sublime-project
]